In [1]:
import pandas as pd
#print(pd.__version__)

In [2]:
data = pd.Series([2,3,4,5,6,7,8],name="Marks",
                 index=['a','b','c','d','e','f','g'])
data

a    2
b    3
c    4
d    5
e    6
f    7
g    8
Name: Marks, dtype: int64

In [3]:
data_frame = pd.DataFrame([["Hasnain",17,"Male"],
                           ["Umer",21,"Male"],
                           ["Ali",20,"Male"]],columns=["Name","Age","Gender"],index=["Std-1","Std-2","Std-3"])
data_frame

          Name  Age Gender
Std-1  Hasnain   17   Male
Std-2     Umer   21   Male
Std-3      Ali   20   Male

In [4]:
data_frame["Name"]

Std-1    Hasnain
Std-2       Umer
Std-3        Ali
Name: Name, dtype: str

In [5]:
data_frame.Name

Std-1    Hasnain
Std-2       Umer
Std-3        Ali
Name: Name, dtype: str

In [6]:
data_frame.loc["Std-1"]  # for row wise

Name      Hasnain
Age            17
Gender       Male
Name: Std-1, dtype: object

In [7]:
data = [{"Name":'Yasir',"Science":40,"Math":50,"Urdu":60,"English":70,"Sindhi":90},
        {"Name":'Ahmed',"Scince":59,"Math":90,"Urdu":75,"English":80,"Sindhi":91},
        {"Name":'Ali',"Scince":40,"Math":50,"Urdu":None,"English":70,"Sindhi":90},
        {"Name":"Hasnain","Scince":40,"Math":50,"Urdu":60,"English":70,"Sindhi":90}]
df = pd.DataFrame(data,index=['Std-1','Std-2','Std-3',"Std-4"])
df

          Name  Science  Math  Urdu  English  Sindhi  Scince
Std-1    Yasir     40.0    50  60.0       70      90     NaN
Std-2    Ahmed      NaN    90  75.0       80      91    59.0
Std-3      Ali      NaN    50   NaN       70      90    40.0
Std-4  Hasnain      NaN    50  60.0       70      90    40.0

In [8]:
df[["Name","Scince"]].loc[["Std-1","Std-2"]]

        Name  Scince
Std-1  Yasir     NaN
Std-2  Ahmed    59.0

In [9]:
df.iloc[2:4,:4] #first Row Then Column  and use indexes

          Name  Science  Math  Urdu
Std-3      Ali      NaN    50   NaN
Std-4  Hasnain      NaN    50  60.0

In [10]:
df.info()

<class 'pandas.DataFrame'>
Index: 4 entries, Std-1 to Std-4
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     4 non-null      str
 1   Science  1 non-null      float64
 2   Math     4 non-null      int64
 3   Urdu     3 non-null      float64
 4   English  4 non-null      int64
 5   Sindhi   4 non-null      int64
 6   Scince   3 non-null      float64
dtypes: float64(3), int64(3), str(1)
memory usage: 428.0+ bytes

In [11]:
df = df.astype({"English":str})
df

          Name  Science  Math  Urdu English  Sindhi  Scince
Std-1    Yasir     40.0    50  60.0      70      90     NaN
Std-2    Ahmed      NaN    90  75.0      80      91    59.0
Std-3      Ali      NaN    50   NaN      70      90    40.0
Std-4  Hasnain      NaN    50  60.0      70      90    40.0

In [12]:
df.info()

<class 'pandas.DataFrame'>
Index: 4 entries, Std-1 to Std-4
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     4 non-null      str
 1   Science  1 non-null      float64
 2   Math     4 non-null      int64
 3   Urdu     3 non-null      float64
 4   English  4 non-null      str
 5   Sindhi   4 non-null      int64
 6   Scince   3 non-null      float64
dtypes: float64(3), int64(2), str(2)
memory usage: 428.0+ bytes

In [13]:
student_data = pd.read_csv("Students1.csv")
#student_data
student_data.head(6)

   English  Urdu  Sindhi  Science  Math
0       50  70.0    90.0     80.0    85
1       55  72.0    60.0     70.0    75
2       80  50.0     NaN     83.0    65
3       50  60.0    80.0      NaN    65
4       53  40.0    83.0     70.0    95
5       50   NaN    87.0     80.0    45

In [14]:
student_data.tail()

   English  Urdu  Sindhi  Science  Math
5       50   NaN    87.0     80.0    45
6       40  73.0    60.0     70.0    55
7       59  75.0    60.0     30.0    65
8       68  60.0    80.0     30.0    75
9       58  70.0    50.0     80.0    65

In [15]:
student_data.columns

Index(['English', 'Urdu', 'Sindhi', 'Science', 'Math'], dtype='str')

In [16]:
student_data.index

RangeIndex(start=0, stop=10, step=1)

In [17]:
student_data.describe()

         English       Urdu     Sindhi    Science       Math
count  10.000000   9.000000   9.000000   9.000000  10.000000
mean   56.300000  63.333333  72.222222  65.888889  69.000000
std    11.086027  11.926860  14.635383  20.966905  14.298407
min    40.000000  40.000000  50.000000  30.000000  45.000000
25%    50.000000  60.000000  60.000000  70.000000  65.000000
50%    54.000000  70.000000  80.000000  70.000000  65.000000
75%    58.750000  72.000000  83.000000  80.000000  75.000000
max    80.000000  75.000000  90.000000  83.000000  95.000000

In [18]:
student_data.isna().sum()  # na is not a number value

English    0
Urdu       1
Sindhi     1
Science    1
Math       0
dtype: int64

In [19]:
student_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   English  10 non-null     int64
 1   Urdu     9 non-null      float64
 2   Sindhi   9 non-null      float64
 3   Science  9 non-null      float64
 4   Math     10 non-null     int64
dtypes: float64(3), int64(2)
memory usage: 532.0 bytes

In [20]:
student_data.duplicated().sum()

np.int64(0)

In [21]:
student_data.sum(axis=1)

0    375.0
1    332.0
2    278.0
3    255.0
4    341.0
5    262.0
6    298.0
7    289.0
8    313.0
9    323.0
dtype: float64

In [22]:
student_data.max()

English    80.0
Urdu       75.0
Sindhi     90.0
Science    83.0
Math       95.0
dtype: float64

In [23]:
subject_max = student_data.idxmax()
subject_max

English    2
Urdu       7
Sindhi     0
Science    2
Math       4
dtype: int64

In [24]:
subject_max.values

array([2, 7, 0, 2, 4])

In [25]:
subject_max.index

Index(['English', 'Urdu', 'Sindhi', 'Science', 'Math'], dtype='str')

In [26]:
coustomers = pd.read_csv("Orders.csv")

     order_id customer_id product_id  quantity  order_date
0      O00001       C0333       P022         1  2022-01-09
1      O00002       C0068       P090         1  2022-01-27
2      O00003       C0483       P021         1  2022-01-17
3      O00004       C0214       P076         4  2022-01-07
4      O00005       C0411       P073         4  2022-01-12
...       ...         ...        ...       ...         ...
2579   O02580       C0237       P098         5  2024-12-22
2580   O02581       C0236       P007         1  2024-12-05
2581   O02582       C0029       P035         1  2024-12-12
2582   O02583       C0171       P077         1  2024-12-16
2583   O02584       C0421       P038         5  2024-12-01

[2584 rows x 5 columns]

In [28]:
coustomers.customer_id.mode()

0    C0028
1    C0113
Name: customer_id, dtype: str