In [1]:
import pandas as pd

In [41]:
Category = pd.read_csv("Products.csv")
Orders = pd.read_csv("Orders.csv")
Customer = pd.read_csv("Customer.csv")

In [42]:
merged_data = pd.merge(Orders,Category,on="product_id")
merged_data.order_date = pd.to_datetime(merged_data.order_date)
merged_data["Month"] = merged_data.order_date.dt.month
merged_data["Year"] = merged_data.order_date.dt.year
merged_data

,order_id,customer_id,product_id,quantity,order_date,product_name,category,price,Month,Year
0,O00001,C0333,P022,1,2022-01-09,Tax,Home,185.33,1,2022
1,O00002,C0068,P090,1,2022-01-27,Perform,Electronics,947.55,1,2022
2,O00003,C0483,P021,1,2022-01-17,Art,Electronics,938.65,1,2022
3,O00004,C0214,P076,4,2022-01-07,Amount,Electronics,154.17,1,2022
4,O00005,C0411,P073,4,2022-01-12,Second,Electronics,131.85,1,2022
...,...,...,...,...,...,...,...,...,...,...
2579,O02580,C0237,P098,5,2024-12-22,Decision,Accessories,567.31,12,2024
2580,O02581,C0236,P007,1,2024-12-05,Finish,Clothing,325.74,12,2024
2581,O02582,C0029,P035,1,2024-12-12,First,Clothing,362.04,12,2024
2582,O02583,C0171,P077,1,2024-12-16,Government,Clothing,233.11,12,2024
2583,O02584,C0421,P038,5,2024-12-01,Black,Electronics,817.52,12,2024

In [39]:
m_sell_cat = merged_data.groupby("category")['quantity'].sum()
m_sell_cat.idxmax()

'Electronics'

In [44]:
merged_data["Order_price"] = merged_data.quantity*merged_data.price
merged_data

,order_id,customer_id,product_id,quantity,order_date,product_name,category,price,Month,Year,Order_price
0,O00001,C0333,P022,1,2022-01-09,Tax,Home,185.33,1,2022,185.33
1,O00002,C0068,P090,1,2022-01-27,Perform,Electronics,947.55,1,2022,947.55
2,O00003,C0483,P021,1,2022-01-17,Art,Electronics,938.65,1,2022,938.65
3,O00004,C0214,P076,4,2022-01-07,Amount,Electronics,154.17,1,2022,616.68
4,O00005,C0411,P073,4,2022-01-12,Second,Electronics,131.85,1,2022,527.40
...,...,...,...,...,...,...,...,...,...,...,...
2579,O02580,C0237,P098,5,2024-12-22,Decision,Accessories,567.31,12,2024,2836.55
2580,O02581,C0236,P007,1,2024-12-05,Finish,Clothing,325.74,12,2024,325.74
2581,O02582,C0029,P035,1,2024-12-12,First,Clothing,362.04,12,2024,362.04
2582,O02583,C0171,P077,1,2024-12-16,Government,Clothing,233.11,12,2024,233.11
2583,O02584,C0421,P038,5,2024-12-01,Black,Electronics,817.52,12,2024,4087.60

In [47]:
merged_data.groupby("category")["price"].sum()

category
Accessories    294484.79
Clothing       223388.21
Electronics    315613.14
Footwear       255515.91
Home           279770.78
Name: price, dtype: float64

In [57]:
pivot_table = merged_data.pivot_table(columns=)

IndexError: Column(s) category already selected