In [1]:
import pandas as pd

In [7]:
Student_Data = pd.read_csv("Student.csv")

In [8]:
Student_Data

           roll_no           name  exam1  exam2  final_exam
0    SMIT/DSAI/001    David Iqbal     20     16          35
1    SMIT/DSAI/002    Ahmed Ahmed     13      7          40
2    SMIT/DSAI/003     John Zahid     13     24          47
3    SMIT/DSAI/004    David Brown      0     15          24
4    SMIT/DSAI/005    Fatima Khan     20      8           6
..             ...            ...    ...    ...         ...
495   SMIT/MAW/096     Sara Zahid      8     10          45
496   SMIT/MAW/097     Ayesha Ali     14      3          31
497   SMIT/MAW/098  Michael Brown      2     20          50
498   SMIT/MAW/099     Sara Malik     24      6          16
499   SMIT/MAW/100       Noor Ali      9     11          44

[500 rows x 5 columns]

In [19]:
Student_Data["Class"] = Student_Data["roll_no"].str.split("/").str[1]

SyntaxError: invalid syntax (607387770.py, line 1)

In [22]:
Student_Data["Obtain"] = Student_Data.iloc[:,2:-1].sum(axis = 1)

In [23]:
Student_Data

           roll_no           name  exam1  exam2  final_exam Class  Obtain
0    SMIT/DSAI/001    David Iqbal     20     16          35  DSAI      71
1    SMIT/DSAI/002    Ahmed Ahmed     13      7          40  DSAI      60
2    SMIT/DSAI/003     John Zahid     13     24          47  DSAI      84
3    SMIT/DSAI/004    David Brown      0     15          24  DSAI      39
4    SMIT/DSAI/005    Fatima Khan     20      8           6  DSAI      34
..             ...            ...    ...    ...         ...   ...     ...
495   SMIT/MAW/096     Sara Zahid      8     10          45   MAW      63
496   SMIT/MAW/097     Ayesha Ali     14      3          31   MAW      48
497   SMIT/MAW/098  Michael Brown      2     20          50   MAW      72
498   SMIT/MAW/099     Sara Malik     24      6          16   MAW      46
499   SMIT/MAW/100       Noor Ali      9     11          44   MAW      64

[500 rows x 7 columns]

In [26]:
Student_Data["Total"] = 100

In [27]:
Student_Data

,roll_no,name,exam1,exam2,final_exam,Class,Obtain,Total Marks,Total
0,SMIT/DSAI/001,David Iqbal,20,16,35,DSAI,71,100,100
1,SMIT/DSAI/002,Ahmed Ahmed,13,7,40,DSAI,60,100,100
2,SMIT/DSAI/003,John Zahid,13,24,47,DSAI,84,100,100
3,SMIT/DSAI/004,David Brown,0,15,24,DSAI,39,100,100
4,SMIT/DSAI/005,Fatima Khan,20,8,6,DSAI,34,100,100
...,...,...,...,...,...,...,...,...,...
495,SMIT/MAW/096,Sara Zahid,8,10,45,MAW,63,100,100
496,SMIT/MAW/097,Ayesha Ali,14,3,31,MAW,48,100,100
497,SMIT/MAW/098,Michael Brown,2,20,50,MAW,72,100,100
498,SMIT/MAW/099,Sara Malik,24,6,16,MAW,46,100,100
499,SMIT/MAW/100,Noor Ali,9,11,44,MAW,64,100,100

In [28]:
Student_Data["Percentage"] = (Student_Data.Obtain/Student_Data.Total)*100

In [29]:
Student_Data

,roll_no,name,exam1,exam2,final_exam,Class,Obtain,Total Marks,Total,Percentage
0,SMIT/DSAI/001,David Iqbal,20,16,35,DSAI,71,100,100,71.0
1,SMIT/DSAI/002,Ahmed Ahmed,13,7,40,DSAI,60,100,100,60.0
2,SMIT/DSAI/003,John Zahid,13,24,47,DSAI,84,100,100,84.0
3,SMIT/DSAI/004,David Brown,0,15,24,DSAI,39,100,100,39.0
4,SMIT/DSAI/005,Fatima Khan,20,8,6,DSAI,34,100,100,34.0
...,...,...,...,...,...,...,...,...,...,...
495,SMIT/MAW/096,Sara Zahid,8,10,45,MAW,63,100,100,63.0
496,SMIT/MAW/097,Ayesha Ali,14,3,31,MAW,48,100,100,48.0
497,SMIT/MAW/098,Michael Brown,2,20,50,MAW,72,100,100,72.0
498,SMIT/MAW/099,Sara Malik,24,6,16,MAW,46,100,100,46.0
499,SMIT/MAW/100,Noor Ali,9,11,44,MAW,64,100,100,64.0

In [57]:
def Grade(x):
    if x >= 80:
        return "A"
    elif x >= 60:
        return "B"
    elif x >= 40:
        return "C"
    elif x < 40:
        return "F"

In [58]:
Student_Data["Grades"] = Student_Data.Percentage.apply(Grade)

In [59]:
Student_Data["Rank"] = Student_Data.Percentage.sort_values().index+1
Student_Data

,roll_no,name,exam1,exam2,final_exam,Class,Obtain,Total Marks,Total,Percentage,Grades,Rank
0,SMIT/DSAI/001,David Iqbal,20,16,35,DSAI,71,100,100,71.0,B,155
1,SMIT/DSAI/002,Ahmed Ahmed,13,7,40,DSAI,60,100,100,60.0,B,72
2,SMIT/DSAI/003,John Zahid,13,24,47,DSAI,84,100,100,84.0,A,89
3,SMIT/DSAI/004,David Brown,0,15,24,DSAI,39,100,100,39.0,F,143
4,SMIT/DSAI/005,Fatima Khan,20,8,6,DSAI,34,100,100,34.0,F,175
...,...,...,...,...,...,...,...,...,...,...,...,...
495,SMIT/MAW/096,Sara Zahid,8,10,45,MAW,63,100,100,63.0,B,292
496,SMIT/MAW/097,Ayesha Ali,14,3,31,MAW,48,100,100,48.0,C,373
497,SMIT/MAW/098,Michael Brown,2,20,50,MAW,72,100,100,72.0,B,233
498,SMIT/MAW/099,Sara Malik,24,6,16,MAW,46,100,100,46.0,C,406
499,SMIT/MAW/100,Noor Ali,9,11,44,MAW,64,100,100,64.0,B,392

In [1]:
grp_std = Student_Data.groupby("Class")

NameError: name 'Student_Data' is not defined

In [61]:
DSAI = grp_std.get_group("DSAI")

In [68]:
DSAI["Rank"].sort_values()[:]

98      8
69     12
97     13
81     14
44     27
     ...
28    486
42    490
21    493
27    494
78    495
Name: Rank, Length: 100, dtype: int64